name: yt-transcribe
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Core Python
  - python=3.9
  - pip

  # Torch stack
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - ffmpeg

  # Web server
  - flask
  - gunicorn

  # Playwright + yt-dlp
  - pip:
      - yt-dlp
      - playwright
      - requests
      - urllib3
