model_size: large        # default model
max_concurrency: 1
cache_dir: ./hf_cache

allow_cpu_fallback: true
acquire_timeout_seconds: 2
safe_chunk_size: 10

gpu:
  policy: fixed
  id: 0
  exclude: []

preload_gpu_models:
  - large-v2
  - medium
  - medium.en
  - small
  - small.en
  - base
  - base.en
  - tiny
  - tiny.en
preload_gpu_compute_type: int8_float16
